services:
  dev:
    image: tilerender
    build: .
    ports: [ 3248:3248 ]
    networks: [ websockify ]
    volumes: [ .:/app ]
    logging:
      driver: none
    environment:
      INTERFACE_PORT: 3248

networks:
  websockify:
    name: websockify-proxy
    external: true
